# Generated by Django 4.2.13 on 2024-06-15 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('internship_name', models.CharField(max_length=100)),
                ('internship_description', models.TextField()),
                ('internship_logo', models.ImageField(upload_to='home')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
