# Generated by Django 4.2.13 on 2024-06-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_jobs_alter_internships_internship_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='apply_link',
            field=models.CharField(max_length=300),
        ),
    ]
